syntax enable
set colorcolumn=80

set expandtab
set shiftwidth=4
set autoindent
set smartindent

" `directory` is a special global, controlling the location of swap files.
silent !mkdir -p '/home/pablobm/.local/state/vim/swp'
set directory^=/home/pablobm/.local/state/vim/swp

" Remove trailing spaces on save, on any file (`*`)
autocmd BufWritePre * :%s/\s\+$//e

"
" Terminal
"

set termguicolors " Colors by default
set shell=fish

"
" Packages
"

" First ensure that vim-plug is installed
let config_dir = '~/.config/vim'
if empty(glob(config_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.config_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Now actually install packages
call plug#begin()

Plug 'tpope/vim-sensible'

Plug 'dracula/vim', { 'as': 'dracula' }

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'mileszs/ack.vim'
Plug 'preservim/nerdtree'
Plug 'tpope/vim-fugitive'

call plug#end()

"
" Package configurations
"

colorscheme dracula

nmap <c-p> :GFiles<cr>
let g:fzf_vim = {}

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif
cnoreabbrev Ag Ack
